import { e as createAstro, f as createComponent, r as renderTemplate, j as renderComponent, m as maybeRenderHead, h as addAttribute, l as renderTransition } from '../astro_SLRudV6K.mjs';
import 'kleur/colors';
import { $ as $$Layout } from './404_DUAG0DTE.mjs';
/* empty css                                  */
/* empty css                          */

var __freeze = Object.freeze;
var __defProp = Object.defineProperty;
var __template = (cooked, raw) => __freeze(__defProp(cooked, "raw", { value: __freeze(raw || cooked.slice()) }));
var _a;
const $$Astro = createAstro("https://castelll0009.github.io");
const $$Carnetdigital = createComponent(async ($$result, $$props, $$slots) => {
  const Astro2 = $$result.createAstro($$Astro, $$props, $$slots);
  Astro2.self = $$Carnetdigital;
  return renderTemplate(_a || (_a = __template(["", '<script>\n  const card = document.querySelector(".card");\n\n  function clickRotate() {\n    card.classList.toggle("rotated");\n  }\n  card.addEventListener("click", clickRotate);\n<\/script>'])), renderComponent($$result, "Layout", $$Layout, { "title": "UniKit", "subtitle": "Carnet Digital Unicauca", "data-astro-cid-yhh3bgey": true }, { "default": ($$result2) => renderTemplate`${maybeRenderHead()}<section class="section flex flex-col gap-5 justify-between items-center" style="padding: 5.6vw" data-astro-cid-yhh3bgey${addAttribute(renderTransition($$result2, "fit3apal", "", "homologacion"), "data-astro-transition-scope")}><h1 class="text-secondary dark:text-white" data-astro-cid-yhh3bgey>Carnet Digital Unicauca</h1><!-- <div class="card rotated">
            <Carnet ></Carnet>
           
        </div>     --><div class="card rotated rounded-[3px]" style="width: 7.5cm; height: 11.5cm;" data-astro-cid-yhh3bgey><div class="card-contents card-back" data-astro-cid-yhh3bgey><div class="card-depth flex flex-col items-center text-black h-full" style="width: 100%; padding: 0; margin: 0px;" data-astro-cid-yhh3bgey><!-- header --><div class="flex-1 w-full  relative" style="max-height: 106px; " data-astro-cid-yhh3bgey><div class="flex justify-end w-full px-4 pt-2" style="background: red;" data-astro-cid-yhh3bgey><button id="dropdownButton" data-dropdown-toggle="dropdown" class="inline-block text-gray-500 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700 focus:ring-4 focus:outline-none focus:ring-gray-200 dark:focus:ring-gray-700 rounded-lg text-sm p-1.5" type="button" data-astro-cid-yhh3bgey><span class="sr-only" data-astro-cid-yhh3bgey>Open dropdown</span><svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 16 3" data-astro-cid-yhh3bgey><path d="M2 0a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3Zm6.041 0a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM14 0a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3Z" data-astro-cid-yhh3bgey></path></svg></button><!-- Dropdown menu --><div id="dropdown" class="z-10 hidden text-base list-none bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700" data-astro-cid-yhh3bgey><ul class="py-2" aria-labelledby="dropdownButton" data-astro-cid-yhh3bgey><li data-astro-cid-yhh3bgey><a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white" data-astro-cid-yhh3bgey>Edit</a></li><li data-astro-cid-yhh3bgey><a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white" data-astro-cid-yhh3bgey>Export Data</a></li><li data-astro-cid-yhh3bgey><a href="#" class="block px-4 py-2 text-sm text-red-600 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white" data-astro-cid-yhh3bgey>Delete</a></li></ul></div></div><span class="w-full flex flex-row gap-5 p-2  justify-start" style="min-width: 100%; background: #1d3585; padding-top: 3px; padding-left: 30px; height: 70px;
              background: linear-gradient(88deg, #1A3484, #1a3485 40%, #1a348599);" data-astro-cid-yhh3bgey><span class="absolute " style="min-width: 120px;
            height: 90px;
            background: #1d3585;
            position: absolute;
            z-index: 0;
            margin-left: -24px;
            margin-top: -14px;
            border-radius: 100%;" data-astro-cid-yhh3bgey></span><img class="" src="https://simca.unicauca.edu.co/simca/resources/images/logo.png" alt="" style="filter: invert(0); width: 160px; padding-left: 1px;" data-astro-cid-yhh3bgey></span></div><!-- picture --><div class="flex-1 h-[30%] overflow-hidden" style="height: 30%;" data-astro-cid-yhh3bgey><span class="overflow-hidden relative" style="width: 100px;height: 130px;" data-astro-cid-yhh3bgey><img class="mb-3 block rounded-xs shadow-lg" src="https://i.pinimg.com/564x/f8/f8/2d/f8f82dbfc0b9ffeacc811024ac9882e5.jpg" alt="person image" style="width: 2.8cm; height:3.7cm; margin: 20px" data-astro-cid-yhh3bgey></span></div><!-- footer --><div class="flex-1 h-[30%] overflow-hidden flex flex-col w-full" style="height: 30%;" data-astro-cid-yhh3bgey><h5 class="mb-0 text-xl capitalize" data-astro-cid-yhh3bgey>Jane Doe</h5><h5 class="mb-0 text-xl uppercase" data-astro-cid-yhh3bgey>Jobs galviz</h5><span class="text-sm text-black" data-astro-cid-yhh3bgey>123456789</span><span class="text-sm text-black" data-astro-cid-yhh3bgey>RH. A+</span><div data-astro-cid-yhh3bgey><span class="flex flex-row" style="background:#d53b00; " data-astro-cid-yhh3bgey><div class="flex-1 flex flex-row " style="max-width: 20%;" data-astro-cid-yhh3bgey><span class="w-1 h-fit block " style="background: #f6a500; margin-left: 20px;" data-astro-cid-yhh3bgey></span><span class="w-8 h-fit block " style="background: #f6a500; margin-left: 2px;" data-astro-cid-yhh3bgey></span></div><div class="flex-1" data-astro-cid-yhh3bgey><h6 class="pt-2 pb-2 pl-2 pr-2 text-xl uppercase  w-full text-black font-bold" style="text-align: center; background:#d53b00; " data-astro-cid-yhh3bgey>Estudiante</h6></div><div class="flex-1 flex flex-row " style="max-width: 20%;" data-astro-cid-yhh3bgey></div></span><span class="w-full h-full block " style="background: blue; width: 100%;" data-astro-cid-yhh3bgey></span></div></div></div></div><div class="card-contents card-front" data-astro-cid-yhh3bgey><div class="card-depth" data-astro-cid-yhh3bgey><h2 class="" style="font-size: 2.5rem;" data-astro-cid-yhh3bgey>QR Autenticación</h2><hr data-astro-cid-yhh3bgey><p data-astro-cid-yhh3bgey>Volver al frente</p></div></div></div></section>` }));
}, "C:/Users/CASTELL/Documents/GitHub/ASTRO/Unikit-face-supabase/src/pages/carnetdigital.astro", "self");

const $$file = "C:/Users/CASTELL/Documents/GitHub/ASTRO/Unikit-face-supabase/src/pages/carnetdigital.astro";
const $$url = "/carnetdigital";

export { $$Carnetdigital as default, $$file as file, $$url as url };
